theme: jekyll-theme-minimal
title: Welcome to my Portfolio!
## Shannon McFarland
Senior Plant Science Associate 
Bellevue University Data Science Master Grad (2026)
Biology (BA) (2018)
Contact Me: smcfarland95@gmail.com
